[WIP] Added: the script for the pre-order app and gitignore file(shopify-preorder#01)
hotwax/shopify-preorder-app pull request #2
Opened 2021-08-17 09:27 UTC by ymaheshwari1

- Added the script for pre-order app
- Added a gitignore file
- Added package.json file

2021-08-17 11:16 UTC, adityasharma7 requested changes

2021-08-17 11:16 UTC, adityasharma7 commented on package.json
> +  "scripts": {
Add minification logic as well

2021-08-17 11:33 UTC, ymaheshwari1 commented on package.json
> +  "license": "ISC",
Sir, updated the license.

2021-08-17 11:34 UTC, ymaheshwari1 commented on public/script-tag.js
> +    let jQueryBopis;
Sir, updated the variable name.

2021-08-17 11:34 UTC, ymaheshwari1 commented on package.json
> +  "scripts": {
Sir, added the minification script.

2021-08-24 06:49 UTC, adityasharma7 commented on public/script-tag.js
> +                addToCartButton.after(`<span>Ships from ${ifPreOrderActive.timestamp}</span>`);
Hi @ymaheshwari1,
We will not add entire text after the button, instead find element with `hc_preordershipsfrom` id and add date to it in human readable format.

2021-08-30 07:06 UTC, merged