Implemented login flow(#2h198uc)
hotwax/shopify-preorder-app pull request #34
Opened 2022-06-28 07:48 UTC by disha1202

2022-06-28 09:13 UTC, ymaheshwari1 requested changes

2022-06-28 09:13 UTC, ymaheshwari1 commented on src/services/UserService.ts
> +    return api({
Make indentation consistent.

2022-06-28 09:13 UTC, ymaheshwari1 commented on src/store/modules/user/UserState.ts
> +export default interface ShopState {
```suggestion
export default interface UserState {
```

2022-06-28 09:13 UTC, ymaheshwari1 commented on src/store/modules/user/index.ts
> +export default shopModule;
```suggestion
export default userModule;
```

2022-06-28 09:34 UTC, disha1202 commented on src/services/UserService.ts
> +    return api({
Improved indentation

2022-06-28 09:34 UTC, disha1202 commented on src/store/modules/user/UserState.ts
> +export default interface ShopState {
Made the requested change

2022-06-28 09:34 UTC, disha1202 commented on src/store/modules/user/index.ts
> +const shopModule: Module<UserState, RootState> = {
Made the requested change

2022-06-28 09:34 UTC, disha1202 commented on src/store/modules/user/index.ts
> +export default shopModule;
Made the requested change

2022-06-28 09:35 UTC, disha1202 commented on src/views/Login.vue
> +            <ion-input name="username" v-model="username" id="username"  type="text" required></ion-input>
Used self closing tag.

2022-06-28 11:32 UTC, ymaheshwari1 requested changes

2022-06-28 11:32 UTC, ymaheshwari1 commented on src/store/modules/user/actions.ts
> +          showToast(translate('Sorry, your username or password is incorrect. Please try again.'));
Add it to en.json.

2022-06-28 11:37 UTC, disha1202 commented on src/store/modules/user/actions.ts
> +          showToast(translate('Sorry, your username or password is incorrect. Please try again.'));
Added to en.json

2022-06-28 11:48 UTC, ymaheshwari1 approved these changes

2022-06-30 10:51 UTC, adityasharma7 requested changes

2022-06-30 10:51 UTC, adityasharma7 commented on src/router/index.ts
> +    beforeEnter: authGuard,
We should not add any guard to install page

2022-06-30 10:51 UTC, adityasharma7 commented on src/views/Login.vue
> +      if(!this.baseURL) this.store.dispatch("user/setUserInstanceUrl", this.instanceUrl.trim())
We will use the instanceURL from shop config VUE_APP_SHOPIFY_SHOP_CONFIG

2022-06-30 10:51 UTC, adityasharma7 commented on src/views/Settings.vue
> +      baseURL: process.env.VUE_APP_BASE_URL
We will not store VUE_APP_BASE_URL in configuration in any case. We could remove this

2022-06-30 12:22 UTC, ymaheshwari1 requested changes

2022-06-30 12:22 UTC, ymaheshwari1 commented on src/router/index.ts
> +    beforeEnter: authGuard,
I think we don't need authGuard here.

2022-07-01 08:48 UTC, adityasharma7 requested changes

2022-07-01 08:48 UTC, adityasharma7 commented on src/api/index.ts
> +        baseURL = baseURL && baseURL.startsWith('http') ? baseURL : `https://${baseURL}.hotwax.io/api/`;
Indentation issue

2022-07-01 08:56 UTC, adityasharma7 approved these changes

2022-07-01 08:58 UTC, merged